services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  ad:
    image: osixia/openldap:1.5.0
    container_name: adserver
    restart: always
    environment:
      - LDAP_ORGANISATION=DevOpsTraining
      - LDAP_DOMAIN=devops.lab
      - LDAP_ADMIN_PASSWORD=admin123

    ports:
      - "389:389"
      - "636:636"

    networks:
      - jenkins-net

    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldapadmin
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=adserver
      - PHPLDAPADMIN_HTTPS=false

    ports:
      - "8081:80"

    networks:
      - jenkins-net

volumes:
  jenkins_home:
  ldap_data:
  ldap_config:
networks:
  jenkins-net:
